### ISSUE TITLE
Change ownership to wheresrhys

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/keen-query#148]
We don't use keen any more, but I learned a lot writing this DSL and would like to keep for my own records. So I propose moving this repo out of Financial-Times org and into wheresrhys user

**Comment by adambraimbridge** [comment]
Sounds fine to me. But I was unable to transfer ownership. See if you can do it ...

![image](https://user-images.githubusercontent.com/224547/58092771-db9fcc00-7bc4-11e9-9949-21c38844f6b9.png)
