### ISSUE TITLE
filters - 'not in'

### ISSUE THREAD

**Issue by andygnewman** [Financial-Times/keen-query#16]
Keen currently has an 'in' filter based on values matching against an array provided.

What would be useful is to have a 'not-in' filter, that excludes items that match against a provided list.

An example use case would be to filter outliers from a query, a specific example is that I am filtering out sessions with very large page view counts from analysis of avg page views / ctrs as these outliers can heavily skew the analysis.

Currently I would have to filter against a significantly longer list of 'inliers'.

**Comment by wheresrhys** [comment]
Probably do this today. Have realised that `->filter(user.uuid!?uuid1,uuid2)` can just be an alias to `->filter(user.uuid!=)->filter(user.uuid!=uuid2)`... so easy peasy :-)

**Comment by andygnewman** [comment]
Sounds good. Ta
