### ISSUE TITLE
kq convert fails for queries with no filters

### ISSUE THREAD

**Issue by laurieboyes** [Financial-Times/keen-query#21]
e.g. URL: https://beacon.ft.com/explorer?query%5Bevent_collection%5D=dwell&query%5Banalysis_type%5D=count&query%5Bgroup_by%5D=time.day&query%5Btimezone%5D=UTC&query%5Btimeframe%5D=this_7_days

Appears to be failing at toString() stage

**Comment by wheresrhys** [comment]
v1.4.2
