### ISSUE TITLE
Edge case: "Your query resulted in too many subtimeframes"

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/keen-query#47]
Setting a large timeframe with a small interval ...
![image](https://cloud.githubusercontent.com/assets/224547/12844724/18a62506-cbf9-11e5-9479-a0a691fb4695.png)

... makes keen api ragequit
![image](https://cloud.githubusercontent.com/assets/224547/12844726/1a584a82-cbf9-11e5-904f-653ef655a958.png)

**Comment by wheresrhys** [comment]
Add something here to check for error and throw properly as MVP https://github.com/Financial-Times/keen-query/blob/master/lib/tabulate.js#L79

**Comment by wheresrhys** [comment]
see #82
